[package]
name = "my-redis"
version = "0.1.0"
authors = ["Wembley Leach <wembley@hey.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4.0"
bytes = "1.0.1"
